// Auto-generated by generate_data.py — do not edit by hand
window.RIYA_DATA = {
  "range": {
    "start": "Apr 8, 2026",
    "end": "Apr 22, 2026",
    "days": 15
  },
  "kpis": {
    "sessions": 1754,
    "messages": 32338,
    "avgMsgs": 18.5,
    "medianMsgs": 7,
    "avgPerDay": 116.9,
    "minPerDay": 28,
    "maxPerDay": 194,
    "sessionsDelta": 0.0,
    "messagesDelta": 0.0,
    "avgMsgsDelta": 0.0,
    "dropOffDelta": 0.0
  },
  "daily": [
    {
      "d": "Apr 8",
      "v": 152,
      "day": "Wed"
    },
    {
      "d": "Apr 9",
      "v": 194,
      "day": "Thu"
    },
    {
      "d": "Apr 10",
      "v": 181,
      "day": "Fri"
    },
    {
      "d": "Apr 11",
      "v": 140,
      "day": "Sat"
    },
    {
      "d": "Apr 12",
      "v": 159,
      "day": "Sun"
    },
    {
      "d": "Apr 13",
      "v": 119,
      "day": "Mon"
    },
    {
      "d": "Apr 14",
      "v": 132,
      "day": "Tue"
    },
    {
      "d": "Apr 15",
      "v": 91,
      "day": "Wed"
    },
    {
      "d": "Apr 16",
      "v": 113,
      "day": "Thu"
    },
    {
      "d": "Apr 17",
      "v": 95,
      "day": "Fri"
    },
    {
      "d": "Apr 18",
      "v": 121,
      "day": "Sat"
    },
    {
      "d": "Apr 19",
      "v": 42,
      "day": "Sun"
    },
    {
      "d": "Apr 20",
      "v": 90,
      "day": "Mon"
    },
    {
      "d": "Apr 21",
      "v": 97,
      "day": "Tue"
    },
    {
      "d": "Apr 22",
      "v": 28,
      "day": "Wed"
    }
  ],
  "hourly": [
    24,
    57,
    75,
    61,
    81,
    73,
    106,
    79,
    89,
    85,
    120,
    91,
    90,
    76,
    85,
    154,
    101,
    98,
    84,
    50,
    30,
    11,
    10,
    24
  ],
  "modeSplit": {
    "voice": 744,
    "chat": 1010
  },
  "topicSplit": {
    "free": 1042,
    "scenario": 712
  },
  "depth": {
    "short": {
      "label": "Short ≤4 msgs",
      "voice": 260,
      "chat": 470,
      "total": 730,
      "pct": 41.6
    },
    "medium": {
      "label": "Medium 5–20",
      "voice": 249,
      "chat": 288,
      "total": 537,
      "pct": 30.6
    },
    "long": {
      "label": "Long >20",
      "voice": 235,
      "chat": 252,
      "total": 487,
      "pct": 27.8
    }
  },
  "scenarios": [
    {
      "name": "Talk with Riya",
      "category": "Free Chat",
      "sessions": 1042,
      "avgMsgs": 21.4,
      "dropOff": 31.5,
      "suggChips": 22.1
    },
    {
      "name": "Ordering food at a restaurant",
      "category": "Daily Life",
      "sessions": 262,
      "avgMsgs": 12.8,
      "dropOff": 46.2,
      "suggChips": 13.7
    },
    {
      "name": "Introducing yourself on the first day",
      "category": "Work Communication",
      "sessions": 106,
      "avgMsgs": 18.1,
      "dropOff": 38.7,
      "suggChips": 18.8
    },
    {
      "name": "Buying daily groceries",
      "category": "Daily Life",
      "sessions": 72,
      "avgMsgs": 15.2,
      "dropOff": 45.8,
      "suggChips": 16.2
    },
    {
      "name": "Talking about yourself",
      "category": "Interview Skills",
      "sessions": 65,
      "avgMsgs": 10.6,
      "dropOff": 58.5,
      "suggChips": 11.9
    },
    {
      "name": "Calling customer care",
      "category": "Customer Service",
      "sessions": 22,
      "avgMsgs": 11.6,
      "dropOff": 54.5,
      "suggChips": 12.4
    },
    {
      "name": "Asking for price",
      "category": "Shopping",
      "sessions": 19,
      "avgMsgs": 20.6,
      "dropOff": 42.1,
      "suggChips": 21.2
    },
    {
      "name": "Giving a work update",
      "category": "Work Communication",
      "sessions": 15,
      "avgMsgs": 26.0,
      "dropOff": 46.7,
      "suggChips": 25.6
    },
    {
      "name": "Asking someone to speak slowly",
      "category": "Confidence Building",
      "sessions": 14,
      "avgMsgs": 15.3,
      "dropOff": 42.9,
      "suggChips": 16.1
    },
    {
      "name": "Asking someone for directions",
      "category": "Daily Life",
      "sessions": 11,
      "avgMsgs": 21.8,
      "dropOff": 36.4,
      "suggChips": 22.6
    }
  ],
  "scripts": [
    {
      "name": "Pure English",
      "pct": 90.4,
      "count": 8651
    },
    {
      "name": "Devanagari / Hindi",
      "pct": 7.8,
      "count": 743
    },
    {
      "name": "Hinglish (mixed Roman)",
      "pct": 1.8,
      "count": 173
    },
    {
      "name": "Mixed script",
      "pct": 0.0,
      "count": 4
    }
  ],
  "quality": {
    "avgRiyaWords": 9.1,
    "suggChipsRate": 99.5,
    "loopDetected": 23,
    "abruptDropOff": 661,
    "dropOffByScenario": [
      {
        "name": "Asking a colleague for help",
        "pct": 100
      },
      {
        "name": "Booking a doctor appointment",
        "pct": 75
      },
      {
        "name": "Describing symptoms to a doctor",
        "pct": 75
      },
      {
        "name": "Answering simple problems",
        "pct": 67
      },
      {
        "name": "Making weekend plans",
        "pct": 67
      },
      {
        "name": "Phone banking support",
        "pct": 67
      },
      {
        "name": "Strengths and weaknesses",
        "pct": 67
      },
      {
        "name": "Talking about yourself",
        "pct": 58
      }
    ],
    "loopSamples": [
      {
        "session": "137c00ca",
        "scenario": "Talk with Riya",
        "repeats": 1,
        "snippet": "can you tell me the english word?"
      },
      {
        "session": "1ed785cc",
        "scenario": "Talk with Riya",
        "repeats": 1,
        "snippet": "hey! i'm riya. what do i call you?"
      },
      {
        "session": "2a2d1def",
        "scenario": "Talk with Riya",
        "repeats": 1,
        "snippet": "what do you do after waking up?"
      },
      {
        "session": "2b186308",
        "scenario": "Talk with Riya",
        "repeats": 1,
        "snippet": "hey! i'm riya. what do i call you?"
      }
    ],
    "dropOffSamples": [
      {
        "session": "1d74ebec",
        "scenario": "Talk with Riya",
        "lastUser": "Good morning",
        "lastRiya": "Good morning! It's nice to meet you. What should I call you?",
        "msgCount": 3
      },
      {
        "session": "642b54ae",
        "scenario": "Ordering food at a restaurant",
        "lastUser": "I want to see the menu",
        "lastRiya": "Sure, here's the menu. Are you looking for appetizers, main course, or desserts?",
        "msgCount": 3
      },
      {
        "session": "86c283f2",
        "scenario": "Ordering food at a restaurant",
        "lastUser": "hello",
        "lastRiya": "Oh hi there! I'm Riya. What should I call you?",
        "msgCount": 3
      },
      {
        "session": "b479683a",
        "scenario": "Ordering food at a restaurant",
        "lastUser": "Yes",
        "lastRiya": "Great! What are you in the mood for?",
        "msgCount": 3
      }
    ]
  },
  "topics": [
    {
      "name": "Daily routine & habits",
      "sessions": 208,
      "intent": "practice"
    },
    {
      "name": "Work / career advice",
      "sessions": 173,
      "intent": "practice"
    },
    {
      "name": "Personal life & family",
      "sessions": 130,
      "intent": "personal"
    },
    {
      "name": "Testing the bot",
      "sessions": 115,
      "intent": "exploration"
    },
    {
      "name": "Travel plans",
      "sessions": 104,
      "intent": "practice"
    },
    {
      "name": "Relationships & dating",
      "sessions": 80,
      "intent": "personal"
    },
    {
      "name": "Grammar questions",
      "sessions": 74,
      "intent": "learning"
    },
    {
      "name": "Food & cooking",
      "sessions": 52,
      "intent": "casual"
    }
  ],
  "intents": [
    {
      "name": "Practice",
      "pct": 46
    },
    {
      "name": "Personal",
      "pct": 22
    },
    {
      "name": "Exploration",
      "pct": 14
    },
    {
      "name": "Learning",
      "pct": 10
    },
    {
      "name": "Casual",
      "pct": 8
    }
  ],
  "stallReasons": [
    {
      "reason": "Riya asked too many follow-ups at once",
      "count": 84
    },
    {
      "reason": "User code-switched, Riya stayed English-only",
      "count": 62
    },
    {
      "reason": "Riya's response too long (>40 words)",
      "count": 51
    },
    {
      "reason": "Scenario prompt felt forced / unnatural",
      "count": 44
    },
    {
      "reason": "Riya missed a cultural reference",
      "count": 31
    },
    {
      "reason": "Ambiguous user input, no clarification ask",
      "count": 28
    }
  ],
  "riyaGaps": [
    {
      "gap": "Doesn't respond to Hindi filler words ('haan', 'acha')",
      "count": 72
    },
    {
      "gap": "Over-corrects grammar before responding to meaning",
      "count": 58
    },
    {
      "gap": "Doesn't remember earlier context in same session",
      "count": 47
    },
    {
      "gap": "Defaults to formal register, user wants casual",
      "count": 39
    },
    {
      "gap": "Doesn't acknowledge emotional content",
      "count": 24
    }
  ],
  "_histo": [
    {
      "label": "1",
      "v": 285
    },
    {
      "label": "2",
      "v": 344
    },
    {
      "label": "3",
      "v": 32
    },
    {
      "label": "4",
      "v": 69
    },
    {
      "label": "5-6",
      "v": 117
    },
    {
      "label": "7-8",
      "v": 118
    },
    {
      "label": "9-10",
      "v": 60
    },
    {
      "label": "11-15",
      "v": 152
    },
    {
      "label": "16-20",
      "v": 90
    },
    {
      "label": "21-30",
      "v": 143
    },
    {
      "label": "31-50",
      "v": 159
    },
    {
      "label": "51+",
      "v": 185
    }
  ],
  "_heatData": [
    [
      13,
      9,
      32,
      47,
      50,
      43,
      12,
      3
    ],
    [
      23,
      33,
      46,
      34,
      28,
      45,
      14,
      6
    ],
    [
      11,
      23,
      33,
      46,
      74,
      60,
      20,
      4
    ],
    [
      26,
      41,
      64,
      36,
      25,
      63,
      43,
      9
    ],
    [
      30,
      41,
      51,
      29,
      34,
      48,
      35,
      8
    ],
    [
      35,
      35,
      23,
      36,
      31,
      56,
      30,
      15
    ],
    [
      18,
      33,
      25,
      68,
      9,
      38,
      10,
      0
    ]
  ],
  "_topLong": [
    {
      "session": "7aee7b29",
      "scenario": "Talk with Riya",
      "mode": "Chat",
      "messages": 306,
      "duration": "39m 00s"
    },
    {
      "session": "00e5e91c",
      "scenario": "Giving a work update",
      "mode": "Chat",
      "messages": 267,
      "duration": "15m 00s"
    },
    {
      "session": "db189eb6",
      "scenario": "Talk with Riya",
      "mode": "Voice",
      "messages": 229,
      "duration": "32m 00s"
    },
    {
      "session": "fca24d6e",
      "scenario": "Talk with Riya",
      "mode": "Chat",
      "messages": 172,
      "duration": "31m 00s"
    },
    {
      "session": "35db0b25",
      "scenario": "Introducing yourself on the first day",
      "mode": "Chat",
      "messages": 167,
      "duration": "17m 00s"
    },
    {
      "session": "c1b6cb14",
      "scenario": "Asking someone for directions",
      "mode": "Chat",
      "messages": 164,
      "duration": "30m 00s"
    }
  ],
  "_openingMessages": [
    {
      "label": "hello?",
      "v": 36
    },
    {
      "label": "hello.",
      "v": 26
    },
    {
      "label": "yes.",
      "v": 15
    },
    {
      "label": "yes",
      "v": 14
    },
    {
      "label": "hi",
      "v": 11
    },
    {
      "label": "hello",
      "v": 9
    },
    {
      "label": "hii",
      "v": 6
    },
    {
      "label": "hi.",
      "v": 6
    },
    {
      "label": "you can call me rahul.",
      "v": 5
    },
    {
      "label": "you can call me [name]",
      "v": 5
    }
  ],
  "_singleWord": [
    {
      "label": "yes",
      "v": 171
    },
    {
      "label": "hello?",
      "v": 131
    },
    {
      "label": "yes.",
      "v": 89
    },
    {
      "label": "hello.",
      "v": 67
    },
    {
      "label": "no",
      "v": 59
    },
    {
      "label": "hello",
      "v": 25
    },
    {
      "label": "hi",
      "v": 25
    },
    {
      "label": "ok",
      "v": 23
    },
    {
      "label": "hi.",
      "v": 18
    },
    {
      "label": "okay.",
      "v": 15
    }
  ],
  "_phrases": [
    {
      "label": "no, that's all.",
      "v": 13
    },
    {
      "label": "no, thank you.",
      "v": 13
    },
    {
      "label": "i like",
      "v": 11
    },
    {
      "label": "how are you?",
      "v": 10
    },
    {
      "label": "my name is",
      "v": 9
    },
    {
      "label": "i'm from delhi.",
      "v": 9
    },
    {
      "label": "thank you.",
      "v": 9
    },
    {
      "label": "how are you",
      "v": 7
    },
    {
      "label": "hello riya!",
      "v": 7
    },
    {
      "label": "i am fine.",
      "v": 7
    }
  ],
  "_voiceAvgWords": 4.7,
  "_chatAvgWords": 4.7,
  "_questionPct": 8.1,
  "_singleWordPct": 16,
  "_freeCnt": 1042
};
